version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: qualiTest 
      POSTGRES_PASSWORD: 123qwe
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qualiTest.com
      PGADMIN_DEFAULT_PASSWORD: 123qwe